<?php
/****************************************************
PayPal-Express-Schnittstelle
Version 1.0
(c)2009, Payintelligent 

constants.php

This is the configuration file.This file defines the parameters 
needed to make an API call.

PayPal includes the following API Signature for making API
calls to the PayPal:

API Username 	sdk-three_api1.sdk.com
API Password 	QFZCWN5HZM8VBG7Q
API Signature 	A-IzJhZZjhg29XQ2qnhapuwxIDzyAZQ92FRP5dqBzVesOkzbdUONzmOU

Called by CallerService.php.
****************************************************/

/**
# API user: The user that is identified as making the call. you can
# also use your own API username that you created on PayPal’s sandbox
# or the PayPal live site
*/

$paypalSandbox = $payment->paypalSandbox;
$paypalUsername = $payment->paypalUsername;
$paypalPassword = $payment->paypalPassword;
$paypalSignature = $payment->paypalSignature;
$paypalAuthorization = $payment->paypalAuthorization;

if ($paypalSandbox == 1) {
	$paypalEndpoint = "https://api-3t.sandbox.paypal.com/nvp";
	$paypalUrl = "https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=";
	$redirectURL = 'https://www.sandbox.paypal.com/webscr?cmd=_complete-express-checkout&token=';
	$payment->sSYSTEM->_SESSION['paypalUrl'] = $paypalUrl;
	$ipnURL = 'www.sandbox.paypal.com';
	
} else {
	$paypalEndpoint = "https://api-3t.paypal.com/nvp";
	$paypalUrl = "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=";
	$redirectURL = 'https://www.paypal.com/webscr?cmd=_complete-express-checkout&token=';
	$payment->sSYSTEM->_SESSION['paypalUrl'] = $paypalUrl;
	$ipnURL = 'www.paypal.com';
}

if ($paypalAuthorization == '1') {
	define('PAYMENT_TYPE', 'Authorization');
} else {
	define('PAYMENT_TYPE', 'Sale');
}

define('API_USERNAME', $paypalUsername);

/**
# API_password: The password associated with the API user
# If you are using your own API username, enter the API password that
# was generated by PayPal below
# IMPORTANT - HAVING YOUR API PASSWORD INCLUDED IN THE MANNER IS NOT
# SECURE, AND ITS ONLY BEING SHOWN THIS WAY FOR TESTING PURPOSES
*/

define('API_PASSWORD', $paypalPassword);

/**
# API_Signature:The Signature associated with the API user. which is generated by paypal.
*/

define('API_SIGNATURE', $paypalSignature);

/**
# Endpoint: this is the server URL which you have to connect for submitting your API request.
*/

define('API_ENDPOINT', $paypalEndpoint);
/**
USE_PROXY: Set this variable to TRUE to route all the API requests through proxy.
like define('USE_PROXY',TRUE);
*/
define('USE_PROXY',FALSE);
/**
PROXY_HOST: Set the host name or the IP address of proxy server.
PROXY_PORT: Set proxy port.

PROXY_HOST and PROXY_PORT will be read only if USE_PROXY is set to TRUE
*/
define('PROXY_HOST', '127.0.0.1');
define('PROXY_PORT', '808');

/* Define the PayPal URL. This is the URL that the buyer is
   first sent to to authorize payment with their paypal account
   change the URL depending if you are testing on the sandbox
   or going to the live PayPal site
   For the sandbox, the URL is
   https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=
   For the live site, the URL is
   https://www.paypal.com/webscr&cmd=_express-checkout&token=
   */
define('PAYPAL_URL', $paypalUrl);

/* Define the PayPal REdirect URL. This is the URL 
   redirect the user to PayPal. PayPal will direct the
   user according to the selected payment methods (e.g. to giropay).
   When redirecting the user to Paypal you need to append the Token-value to the following
   redirect
   */
define('PAYPAL_REDIRECTURL', $redirectURL);

/* Define the PayPal IPN URL. This is the URL 
   send the IPN to PayPal. 
   */
define('PAYPAL_IPNURL', $ipnURL);


/**
# Version: this is the API version in the request.
# It is a mandatory parameter for each API request.
# The only supported value at this time is 2.3
*/

define('VERSION', '53.0');

?>